// fme_id_rom_2.v

// Generated using ACDS version 23.4 79

`timescale 1 ps / 1 ps
module fme_id_rom_2 (
		output wire [63:0] q,       //       q.dataout
		input  wire [2:0]  address, // address.address
		input  wire        clock    //   clock.clk
	);

	fme_id_rom_2_rom_1port_2021_nutbtky rom_1port_0 (
		.q       (q),       //  output,  width = 64,       q.dataout
		.address (address), //   input,   width = 3, address.address
		.clock   (clock)    //   input,   width = 1,   clock.clk
	);

endmodule
