// fme_id_rom_2_rom_1port_intel_mce_2021_iwha2ga.v

// Generated using ACDS version 23.4 79

`timescale 1 ps / 1 ps
module fme_id_rom_2_rom_1port_intel_mce_2021_iwha2ga #(
		parameter SLD_NODE_INFO        = 270036480,
		parameter BYTE_ENABLE_WIDTH    = 1,
		parameter FIFO_SIZE_DELAY      = 5,
		parameter QUEUE_SIZE_WIDTH     = 5,
		parameter LATENCY              = 2,
		parameter WIDTH_WORD           = 64,
		parameter NUMWORDS             = 8,
		parameter WIDTHAD              = 3,
		parameter SHIFT_COUNT_BITS     = 7,
		parameter IS_DATA_IN_RAM       = 1,
		parameter IS_READABLE          = 1,
		parameter BACKPRESSURE_ENABLED = 1,
		parameter FIFO_SIZE            = 16,
		parameter FIFO_SIZE_WIDTH      = 4,
		parameter NODE_NAME_DEC        = 1313820229
	) (
		input  wire        clock0,            //    mm_clk.clk
		output wire        reset_out,         //     reset.reset
		output wire [2:0]  ismce_addr,        // mm_master.address
		output wire [0:0]  ismce_byteena,     //          .byteenable
		output wire [63:0] ismce_wdata,       //          .writedata
		output wire        ismce_wren,        //          .write
		output wire        ismce_rden,        //          .read
		input  wire [63:0] ismce_rdata,       //          .readdata
		input  wire        ismce_waitrequest, //          .waitrequest
		output wire        tck_usr            //   clk_out.clk
	);

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (SLD_NODE_INFO != 270036480)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					sld_node_info_check ( .error(1'b1) );
		end
		if (BYTE_ENABLE_WIDTH != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					byte_enable_width_check ( .error(1'b1) );
		end
		if (FIFO_SIZE_DELAY != 5)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					fifo_size_delay_check ( .error(1'b1) );
		end
		if (QUEUE_SIZE_WIDTH != 5)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					queue_size_width_check ( .error(1'b1) );
		end
		if (LATENCY != 2)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					latency_check ( .error(1'b1) );
		end
		if (WIDTH_WORD != 64)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					width_word_check ( .error(1'b1) );
		end
		if (NUMWORDS != 8)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					numwords_check ( .error(1'b1) );
		end
		if (WIDTHAD != 3)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					widthad_check ( .error(1'b1) );
		end
		if (SHIFT_COUNT_BITS != 7)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					shift_count_bits_check ( .error(1'b1) );
		end
		if (IS_DATA_IN_RAM != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					is_data_in_ram_check ( .error(1'b1) );
		end
		if (IS_READABLE != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					is_readable_check ( .error(1'b1) );
		end
		if (BACKPRESSURE_ENABLED != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					backpressure_enabled_check ( .error(1'b1) );
		end
		if (FIFO_SIZE != 16)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					fifo_size_check ( .error(1'b1) );
		end
		if (FIFO_SIZE_WIDTH != 4)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					fifo_size_width_check ( .error(1'b1) );
		end
		if (NODE_NAME_DEC != 1313820229)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					node_name_dec_check ( .error(1'b1) );
		end
	endgenerate

	sld_mod_ram_rom_top #(
		.SLD_NODE_INFO        (270036480),
		.BYTE_ENABLE_WIDTH    (1),
		.FIFO_SIZE_DELAY      (5),
		.QUEUE_SIZE_WIDTH     (5),
		.LATENCY              (2),
		.WIDTH_WORD           (64),
		.NUMWORDS             (8),
		.WIDTHAD              (3),
		.SHIFT_COUNT_BITS     (7),
		.IS_DATA_IN_RAM       (1),
		.IS_READABLE          (1),
		.BACKPRESSURE_ENABLED (1),
		.FIFO_SIZE            (16),
		.FIFO_SIZE_WIDTH      (4),
		.NODE_NAME_DEC        (1313820229)
	) intel_mce_inst (
		.clock0            (clock0),            //   input,   width = 1,    mm_clk.clk
		.reset_out         (reset_out),         //  output,   width = 1,     reset.reset
		.ismce_addr        (ismce_addr),        //  output,   width = 3, mm_master.address
		.ismce_byteena     (ismce_byteena),     //  output,   width = 1,          .byteenable
		.ismce_wdata       (ismce_wdata),       //  output,  width = 64,          .writedata
		.ismce_wren        (ismce_wren),        //  output,   width = 1,          .write
		.ismce_rden        (ismce_rden),        //  output,   width = 1,          .read
		.ismce_rdata       (ismce_rdata),       //   input,  width = 64,          .readdata
		.ismce_waitrequest (ismce_waitrequest), //   input,   width = 1,          .waitrequest
		.tck_usr           (tck_usr)            //  output,   width = 1,   clk_out.clk
	);

endmodule
